[build]
  base = "apps/web"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[cache]
  command = "node_modules"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"
